### ISSUE TITLE
This looks amazing

### ISSUE THREAD

**Issue by GrindamN** [creatorrr/deck.rocks#1]
Just tested out the demo and I must say it looks amazing. It would be interesting if it could be used to generate movie, book, games recommendation by using API of various platforms such as an reddit, imdb, goodreads etc.

I'm interested in working on project in this area because it could be quite cool to get real recommendations based on what people posted, liked etc.

**Comment by creatorrr** [comment]
Thanks @GrindamN ! Yes absolutely! In its current state, it’s mostly just an interesting prototype but it demonstrates the capabilities of these AI models. 

You could also take a look at the [original notebook](https://runkit.com/diwank/startup-deck-gen) that I experimented with. It’s a much much simpler version that makes it easier to grok the internals. 

Thanks for sharing your thoughts. Would love to keep the conversation going. :)

For instance, how do you think we can improve the current version? Can we make it more accurate and dependable?

**Comment by GrindamN** [comment]
Well I really like the current version and how it creates custom pitch decks. I was thinking it would be amazing if the same could be adapted to use API from let's say Spotify, Goodread, some gaming website, then generate lists with some kind of short summary, tags etc. It would allow project to go beyond Pitch Decks and get something even more awesome.

**Comment by creatorrr** [comment]
Yes certainly. I have been thinking about applying it to academic papers (somehow designed to prevent plagiarism of course)

**Comment by GrindamN** [comment]
> Yes certainly. I have been thinking about applying it to academic papers (somehow designed to prevent plagiarism of course)

That would be interesting use case. When I wrote my master thesis it was ran through that kind of software. One of the key problems there is that some of those count book titles, law citations and similar as copied work, do the models would need to be really trained to recognize the context.

**Comment by creatorrr** [comment]
Closing this issue for now. Feel free to continue the conversation whenever. :)
